### ISSUE TITLE
Unable to build obr with gradle

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/cli#119]
C:\temp\GLTest\com.ibm.cics.test.runtimes>gradle build publishToMavenLocal

> Task :com.ibm.cics.test.runtimes.obr:publishMavenPublicationToMavenLocal
Execution optimizations have been disabled for task ':com.ibm.cics.test.runtimes.obr:publishMavenPublicationToMavenLocal' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'C:\temp\GLTest\com.ibm.cics.test.runtimes\com.ibm.cics.test.runtimes.obr\build\galasa.obr'. Reason: Task ':com.ibm.cics.test.runtimes.obr:publishMavenPublicationToMavenLocal' uses this output of task ':com.ibm.cics.test.runtimes.obr:genobr' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 1s
9 actionable tasks: 5 executed, 4 up-to-date

**Comment by ChrisAtkinson1** [comment]
`26/06/2023 15:42:40.979 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
26/06/2023 15:42:40.980 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
26/06/2023 15:42:40.980 DEBUG d.g.f.FrameworkInitialisation - galasa home used to determine CPS location.
26/06/2023 15:42:40.980 DEBUG d.g.f.FrameworkInitialisation - Configuration Property Store is file:///C:/temp/GLTest/GLHOME/cps.properties
26/06/2023 15:42:40.990 DEBUG d.g.f.FrameworkInitialisation - Selected CPS Service is dev.galasa.framework.internal.cps.FpfConfigurationPropertyStore
26/06/2023 15:42:40.991 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
26/06/2023 15:42:40.991 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
26/06/2023 15:42:40.991 DEBUG d.g.f.FrameworkInitialisation - Dynamic Status Store is file:///C:/temp/GLTest/GLHOME/dss.properties
26/06/2023 15:42:41.006 INFO  d.g.f.FrameworkInitialisation - Submitting test com.ibm.cics.test.runtimes/com.ibm.cicstest.runtimes.liberty.LibertyBasicBVT
26/06/2023 15:42:41.043 INFO  d.g.f.FrameworkInitialisation - Allocated Run Name L22 to this run
26/06/2023 15:42:41.044 INFO  d.g.f.FrameworkInitialisation - Run name is L22
26/06/2023 15:42:41.045 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
26/06/2023 15:42:41.045 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
26/06/2023 15:42:41.046 DEBUG d.g.f.FrameworkInitialisation - Result Archive Stores are [file:///C:/temp/GLTest/GLHOME/ras]
26/06/2023 15:42:41.072 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
26/06/2023 15:42:41.072 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
26/06/2023 15:42:41.073 DEBUG d.g.f.FrameworkInitialisation - Credentials Store is file:///C:/temp/GLTest/GLHOME/credentials.properties
26/06/2023 15:42:41.077 INFO  d.g.f.FrameworkInitialisation - Framework initialised
26/06/2023 15:42:41.091 ERROR d.g.f.TestRunner - Unable to load the test bundle com.ibm.cics.test.runtimes
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "com.ibm.cics.test.runtimes" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1687790560865:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1687790560865:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.27.0.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Unable to locate bundle "com.ibm.cics.test.runtimes" in OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:50) ~[-1687790560865:?]
	... 8 more
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "com.ibm.cics.test.runtimes" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1687790560865:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1687790560865:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.27.0.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Unable to locate bundle "com.ibm.cics.test.runtimes" in OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:50) ~[-1687790560865:?]
	... 8 more
26/06/2023 15:42:41.125 INFO  d.g.f.Framework - Shutting down the framework
26/06/2023 15:42:41.125 INFO  d.g.f.Framework - Framework shutdown`

**Comment by techcobweb** [comment]
Thanks. I've added this issue to the project kan-ban board we use to track issues, so now aware of it... Not doing that means it's less likely to get onto our radar.

**Comment by ChrisAtkinson1** [comment]
I cleared out my .m2 repo

I rebuilt the sample project and my liberty one.

Both now fail the same.  

```
05/07/2023 11:09:25.584 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
05/07/2023 11:09:25.585 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
05/07/2023 11:09:25.585 DEBUG d.g.f.FrameworkInitialisation - galasa home used to determine CPS location.
05/07/2023 11:09:25.586 DEBUG d.g.f.FrameworkInitialisation - Configuration Property Store is file:///C:/temp/GLTest/GLHOME/cps.properties
05/07/2023 11:09:25.599 DEBUG d.g.f.FrameworkInitialisation - Selected CPS Service is dev.galasa.framework.internal.cps.FpfConfigurationPropertyStore
05/07/2023 11:09:25.601 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
05/07/2023 11:09:25.602 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
05/07/2023 11:09:25.602 DEBUG d.g.f.FrameworkInitialisation - Dynamic Status Store is file:///C:/temp/GLTest/GLHOME/dss.properties
05/07/2023 11:09:25.611 INFO  d.g.f.FrameworkInitialisation - Submitting test com.ibm.cics.exampletests.cemt/com.ibm.cics.exampletests.cemt.TestCemt
05/07/2023 11:09:25.667 INFO  d.g.f.FrameworkInitialisation - Allocated Run Name L36 to this run
05/07/2023 11:09:25.667 INFO  d.g.f.FrameworkInitialisation - Run name is L36
05/07/2023 11:09:25.669 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
05/07/2023 11:09:25.669 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
05/07/2023 11:09:25.670 DEBUG d.g.f.FrameworkInitialisation - Result Archive Stores are [file:///C:/temp/GLTest/GLHOME/ras]
05/07/2023 11:09:25.721 INFO  d.g.f.FrameworkInitialisation - System property GALASA_HOME used to set value of home location.
05/07/2023 11:09:25.721 INFO  d.g.f.FrameworkInitialisation - Galasa home location is C:\temp\GLTest\GLHOME
05/07/2023 11:09:25.722 DEBUG d.g.f.FrameworkInitialisation - Credentials Store is file:///C:/temp/GLTest/GLHOME/credentials.properties
05/07/2023 11:09:25.729 INFO  d.g.f.FrameworkInitialisation - Framework initialised
05/07/2023 11:09:26.138 ERROR d.g.f.TestRunner - Unable to load the test bundle com.ibm.cics.exampletests.cemt
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "com.ibm.cics.exampletests.cemt" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1688551765474:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1688551765474:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.27.0.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Bundle failed to install and activate
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:166) ~[-1688551765474:?]
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:53) ~[-1688551765474:?]
	... 8 more
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "com.ibm.cics.exampletests.cemt" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1688551765474:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1688551765474:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [galasa-boot-0.27.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.27.0.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Bundle failed to install and activate
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:166) ~[-1688551765474:?]
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:53) ~[-1688551765474:?]
	... 8 more
05/07/2023 11:09:26.179 INFO  d.g.f.Framework - Shutting down the framework
05/07/2023 11:09:26.179 INFO  d.g.f.Framework - Framework shutdown
```

**Comment by ChrisAtkinson1** [comment]
[mym2.zip](https://github.com/galasa-dev/cli/files/11956792/mym2.zip)

That's my m2 afterbuilding both before running galasactl local init

**Comment by ChrisAtkinson1** [comment]
I have fixed my builds. 

The issue seems to be gradle build publishToMavenLocal does not clean up the repository.  I cleared it out and it now runs.  I have to redelete the repo each build.

Also had to alter the obr to add in some other managers. ( Examples has them - but not in the cli create )

**Comment by ChrisAtkinson1** [comment]
The issue is resolved by this.

gradle build publishToMavenLocal   is wrong.

Should be gradle clean build publishToMavenLocal

**Comment by ChrisAtkinson1** [comment]
Fixed via -> https://github.ibm.com/CICS/cicsts-galasa-sample/pull/13

**Comment by techcobweb** [comment]
> gradle build publishToMavenLocal is wrong.

We can update the docs about that. @CaroMac
